### ISSUE TITLE
config file is not accessed

### ISSUE THREAD

**Issue by Andyzug** [PiSugar/sugar-wifi-conf#1]
HI!
I added this line: sudo /home/pi/sugar-wifi-conf/build/sugar-wifi-conf pisugar /home/pi/sugar-wifi-conf/custom_config.json    in rc.local file but on client side nothing changed

**Comment by Andyzug** [comment]
My bad, I found at the beginning of rc.local between comments a line with 'sudo /home/pi/sugar-wifi-conf/build/sugar-wifi-conf' thats why it didn't use custom_config

**Comment by JdaieLin** [comment]
> My bad, I found at the beginning of rc.local between comments a line with 'sudo /home/pi/sugar-wifi-conf/build/sugar-wifi-conf' thats why it didn't use custom_config

It might be a bug of the shell script adding one more line to rc.local. I will soon fix it.

**Comment by Andyzug** [comment]
> 
> 
> > My bad, I found at the beginning of rc.local between comments a line with 'sudo /home/pi/sugar-wifi-conf/build/sugar-wifi-conf' thats why it didn't use custom_config
> 
> It might be a bug of the shell script adding one more line to rc.local. I will soon fix it.

Hi, after you fixed, now '&' is in the middle of command: 
sudo /home/pi/sugar-wifi-conf/build/sugar-wifi-conf& pisugar /home/pi/sugar-wifi-conf/custom_config.json
it should be at the end of the line to execute whole command, thank you!
