### ISSUE TITLE
PiSugar/sugar-wifi-conf/blob/master/build/sugar-wifi-conf 并不是开源的？

### ISSUE THREAD

**Issue by xueliu** [PiSugar/sugar-wifi-conf#12]
请问 PiSugar/sugar-wifi-conf/blob/master/build/sugar-wifi-conf 并不是开源的？
在这个库里没有找到相应的源码。

**Comment by JdaieLin** [comment]
源码就是工程代码，build里面已经打包好的可执行文件。目前安装流程已经改为本地编译
