### ISSUE TITLE
搜索不到树莓派

### ISSUE THREAD

**Issue by leruge** [PiSugar/sugar-wifi-conf#13]
设备：树莓派4B
操作步骤：
1、wget http://cdn.pisugar.com/release/sugarwificonfig.sh -O- | sh
2、sudo reboot
3、扫码进入小程序“PiSugar”
4、搜索不到树莓派

**Comment by huhuime** [comment]
64位的系统不能直接用，需要补依赖

**Comment by JdaieLin** [comment]
可以使用新的安装流程试试
