### ISSUE TITLE
64bit bullseye 

### ISSUE THREAD

**Issue by hmne** [PiSugar/sugar-wifi-conf#14]
hi the app not starting 

unable to execute

<img width="1109" alt="Screen Shot 2024-01-07 at 5 16 48 PM" src="https://github.com/PiSugar/sugar-wifi-conf/assets/43558467/20a5f26d-6800-4966-901c-06ed4cd596c7">

**Comment by hmne** [comment]
error 

-bash:
./sugar-wifi-conf: No such file or directory

sugar-wifi-conf is in the directory

![860A60A9-00EF-4AD4-AC48-C453BA593521](https://github.com/PiSugar/sugar-wifi-conf/assets/43558467/53c04a22-7fa6-491c-a1b2-f5794e1de970)

**Comment by dadaewqq** [comment]
> error
> 
> -bash: ./sugar-wifi-conf: No such file or directory
> 
> sugar-wifi-conf is in the directory
> 
> ![860A60A9-00EF-4AD4-AC48-C453BA593521](https://private-user-images.githubusercontent.com/43558467/295006713-53c04a22-7fa6-491c-a1b2-f5794e1de970.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk2NTcyNzEsIm5iZiI6MTcxOTY1Njk3MSwicGF0aCI6Ii80MzU1ODQ2Ny8yOTUwMDY3MTMtNTNjMDRhMjItN2ZhNi00OTFjLWExYjItZjU3OTRlMWRlOTcwLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyOVQxMDI5MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYjc4ZDljODBlMGQzYzE0NjM2ZWEwNGRlYTcyMDRmYjZiODJhYmJlNGVmZmMyMTBjNDliNjI5YjRhZjdiMDZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3IlzCJJGU_1t9pFPW3WLUhlRJHmoxNsFtExfIkiyvXw)

缺32位的兼容库：

sudo dpkg --add-architecture armhf
sudo apt update
sudo apt install libc6:armhf libstdc++6:armhf

**Comment by JdaieLin** [comment]
Please try install using the new command in README. It will compiled locally on your pi.
