### ISSUE TITLE
Error after npm run dev in web-bluetooth-client

### ISSUE THREAD

**Issue by punyanagari** [PiSugar/sugar-wifi-conf#5]
Log file:

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/Cellar/node/12.10.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'dev'
1 verbose cli ]
2 info using npm@6.11.3
3 info using node@v12.10.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle web-bluetooth-client@1.0.0~predev: web-bluetooth-client@1.0.0
6 info lifecycle web-bluetooth-client@1.0.0~dev: web-bluetooth-client@1.0.0
7 verbose lifecycle web-bluetooth-client@1.0.0~dev: unsafe-perm in lifecycle true
8 verbose lifecycle web-bluetooth-client@1.0.0~dev: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/$
9 verbose lifecycle web-bluetooth-client@1.0.0~dev: CWD: /Users/Arahasya/blue-pi/web-bluetooth-client
10 silly lifecycle web-bluetooth-client@1.0.0~dev: Args: [
10 silly lifecycle   '-c',
10 silly lifecycle   'webpack-dev-server --inline --progress --config build/webpack.dev.conf.js'
10 silly lifecycle ]
11 silly lifecycle web-bluetooth-client@1.0.0~dev: Returned: code: 1  signal: null
12 info lifecycle web-bluetooth-client@1.0.0~dev: Failed to exec dev script
13 verbose stack Error: web-bluetooth-client@1.0.0 dev: `webpack-dev-server --inline --progress --config build/webpack.dev.conf.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:209:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:209:13)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid web-bluetooth-client@1.0.0
15 verbose cwd /Users/Arahasya/blue-pi/web-bluetooth-client
16 verbose Darwin 18.7.0
17 verbose argv "/usr/local/Cellar/node/12.10.0/bin/node" "/usr/local/bin/npm" "run" "dev"
18 verbose node v12.10.0
19 verbose npm  v6.11.3
20 error code ELIFECYCLE
21 error errno 1

**Comment by JdaieLin** [comment]
hi arahasya
It seems that it's cause by new webpack version. I will fix it in this week.

**Comment by JdaieLin** [comment]
fixed
