### ISSUE TITLE
npm run dev fails.

### ISSUE THREAD

**Issue by Syirrus** [PiSugar/sugar-wifi-conf#8]
Whenever I try to run in the "web-bluetooth-client" directory:
`npm run dev`

I get the following error:

_npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! web-bluetooth-client@1.0.0 dev: `webpack-dev-server --inline --progress --config build/webpack.dev.conf.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the web-bluetooth-client@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above._

Any ideas on how to fix this?

**Comment by fengyc** [comment]
@Syirrus Any detail information of the environment, os, nodejs version, etc.

**Comment by Syirrus** [comment]
Thanks for responding. I'm running the latest node from nodejs on MacOSX (latest). 
I finally was able to get things working and I think the changes I made to the package.json in the webpack modules clinched it. 

I updated (downgraded version of webpack) the following in your package.json:

OLD:
    "webpack-bundle-analyzer": "^3.3.2",
    "webpack-dev-server": "^3.1.11",

NEW (seems to work):
    "webpack-bundle-analyzer": "^2.9.0",
    "webpack-dev-server": "^2.9.1",

**Comment by JdaieLin** [comment]
> Thanks for responding. I'm running the latest node from nodejs on MacOSX (latest).
> I finally was able to get things working and I think the changes I made to the package.json in the webpack modules clinched it.
> 
> I updated (downgraded version of webpack) the following in your package.json:
> 
> OLD:
> "webpack-bundle-analyzer": "^3.3.2",
> "webpack-dev-server": "^3.1.11",
> 
> NEW (seems to work):
> "webpack-bundle-analyzer": "^2.9.0",
> "webpack-dev-server": "^2.9.1",

Looks like a webpack compatibility issue. I have downgraded the version in the latest commit.

**Comment by JdaieLin** [comment]
and receive a security alert suggesting upgrading to webpack-bundle-analyzer 3.3.2...
So this issue is caused by Github autofix robot. 
I will look into this later.

**Comment by Syirrus** [comment]
> and receive a security alert suggesting upgrading to webpack-bundle-analyzer 3.3.2...
> So this issue is caused by Github autofix robot.
> I will look into this later.

Thank you for looking into this. I see that you downgraded webpack-bundle-analyzer.
